### ISSUE TITLE
Maximum update depth exceeded.

### ISSUE THREAD

**Issue by mojjy** [react-component/menu#265]
We are occasionally experiencing the following error in our production environment. Only certain users are experiencing this.  We are using an antd select component,  which uses the react-component/select component, which uses this component.  Sometimes this error occurs when first clicking in the select dropdown, and other times, when selecting the 3rd/4th item in the dropdown. 

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

```
  at listener (client.3713b3bd.js:3614)
vendor.17bd68bdeb41bf6a11e3.js:2573 Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:522
    at a (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:625)
    at Qa (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:95354)
    at Object.enqueueSetState (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:44845)
    at l.x.setState (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2612:1702)
    at Array.r.handleChange (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:1006:710657)
    at Object.setState (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:1006:713027)
    at t.updateMiniStore (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2557:83699)
    at t.componentDidUpdate (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2557:83601)
    at Ba (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:82584)
    at Va (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:85160)
    at https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:98367
    at Object.t.unstable_runWithPriority (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2628:3194)
    at js (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:98302)
    at Cs (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:98078)
    at Es (https://integrate.bmwgroup.net/vendor.17bd68bdeb41bf6a11e3.js:2573:97423)

```

**Comment by ncnt257** [comment]
any update here

**Comment by yoyo837** [comment]
Does the new version still have this problem?
