### ISSUE TITLE
15.5版本下 DOMWrap: React.createClass is deprecated

### ISSUE THREAD

**Issue by blog-lyn** [react-component/menu#81]
15.5 会警告不要从react import,不升级到15.5 其他dependencies 又会报unmet
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
DOMWrap: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```
src/DOMWrap.jsx  中需要修正:
```
// After (15.5)
import React from 'react';
import PropTypes from 'prop-types';
var createReactClass = require('create-react-class');
var Component = createReactClass({})

``` 

看到一天前修改了package.json  lockdown to 15.4 是有什么计划么?
有升级的计划么? 还是可以提mr?

**Comment by afc163** [comment]
来个 PR

https://github.com/ant-design/ant-design/issues/5678

**Comment by blog-lyn** [comment]
好的

**Comment by blog-lyn** [comment]
npm 上 rc-animate没有发布啊,不能通过测试

**Comment by blog-lyn** [comment]
测试用例里 enzyme 貌似不能render出来 

```
 Method “props” is only meant to be run on a single node. 0 found instead.

      at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1419:17)
      at ReactWrapper.props (node_modules/enzyme/build/ReactWrapper.js:796:21)
      at Object.<anonymous> (tests/SubMenu.spec.js:134:49)
```

**Comment by yesmeck** [comment]
@afc163 发下 5.0.10

**Comment by afc163** [comment]
done

**Comment by iamfoxuriel** [comment]
不建议在5.0.9 修改React 15.5.x依赖  
因为这个原因只能回滚antd

**Comment by yesmeck** [comment]
@iamfoxuriel 碰到了什么问题？
